<<<<<<< HEAD
# Generated by Django 6.0.5 on 2026-06-20 15:14
=======
# Generated by Django 6.0.5 on 2026-06-23 00:06
>>>>>>> 942f9598c2ff212e5980520498b90a75b55495d1

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMorosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasGracia', models.PositiveSmallIntegerField(default=3)),
                ('diaCobroMensual', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
    ]
