# Generated by Django 6.0.5 on 2026-06-12 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0010_cliente_fecharegistro'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionMorosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diasGracia', models.PositiveSmallIntegerField(default=3)),
                ('diaCobroMensual', models.PositiveSmallIntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoMorosidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaInicioPendiente', models.DateTimeField(blank=True, null=True)),
                ('fechaUltimaEvaluacion', models.DateTimeField(auto_now=True)),
                ('primeraFacturaGenerada', models.BooleanField(default=False)),
                ('cliente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientoMorosidad', to='core.cliente')),
            ],
        ),
    ]
