# Generated by Django 6.0.5 on 2026-06-15 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('control_morosidad', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SeguimientoMorosidad',
        ),
    ]
